#!/usr/bin/env bash

# Clone Vundle suite
vundle_vim_suite() {
	if [[ ! -d ~/.vim/bundle/Vundle.vim ]]; then
		git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	fi
}

# Config Curator Suite
config_curate_suite() {
	if [[ ! -f ~/.gitconfig ]]; then
		curate -v
	fi
}

# Run the suites
vundle_vim_suite
config_curate_suite

# Upgrade vim plugin
vim +PluginInstall +qall
