#!/usr/bin/env bash

vim_plugins() {
	local destination="~/.vim/bundle/Vundle.vim"

	# Clone the plugin
	if [ ! -d $destination ]; then
		git clone https://github.com/gmarik/Vundle.vim.git $destination
	fi

	# Install the plugin
	vim +PluginInstall +qall
}

vim_plugins
