alias sublime='sublime_text'
alias autochmod='find * -type d -exec chmod 755 {} \;;find * -type f -exec chmod 644 {} \;'
alias makepot='php ~/.wp/dev/tools/i18n/makepot.php'
alias pluginpot='makepot wp-plugin'
alias svnpng='svn propset svn:mime-type image/png *'
